type: witty_object_segmentation
name: witty_egg_carton_top
display_name: Witty Egg Carton Top
model_path: /home/vincent/dev/wittymachines/src/object_detection/weights/rtmdet_egg_cartons_top
classes:
  - egg_carton_top
task: egg_carton_top
conf_threshold: 0.1